### ISSUE TITLE
fix: "OAuth account not linked" error message on login

### ISSUE THREAD

**Issue by denisebitca** [42Atomys/stud42#271]
On trying to log into the open beta with 42 OAuth, I'm getting the error "OAuth account not linked - Your account is not linked to your email. Contact support on Discord".

**To Reproduce**
Steps to reproduce the behavior (_mainly a theory, I am not sure this is the problem_):
1. Get a 42 account that did not sponsor the project and tried to connect to the page before the beta opened up to the public
2. Try to log into the main page

**Expected behavior**
A successful login

**Desktop:**
 - OS: Ubuntu 22.10
 - Browser: Firefox
 - Version: 02.5.0esr

**Comment by 42Atomys** [comment]
Thanks for your report, this issue will be fixed asap due to severity

**Comment by 42Atomys** [comment]
Deployment in progress : https://github.com/42Atomys/stud42/actions/runs/3553414589
