### ISSUE TITLE
misc: Why does the app wants Github write access?

### ISSUE THREAD

**Issue by Antoine-lb** [42Atomys/stud42#275]
Hello, nice that you are doing a refresh to this very useful app.

But I was surprised to know that you **need** to give write access to my public repositories, why is that?

Thanks, have a great day.

**Comment by 42Atomys** [comment]
Hello, happy to see you here, 

Intresting thing, the Github permission wanted to "Star a repository" is "write public repositories", that is why

Usage in code base : 
https://github.com/42Atomys/stud42/blob/main/internal/api/account_callbacks.go#LL67-L69

Github documentation about that : 
https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#:~:text=Also%20required%20for%20starring%20public%20repositories

I hope it answers your question :)

**Comment by 42Atomys** [comment]
(miss clicked, discussion will be disabled)

@Antoine-lb fell free to close the issue if you don't have no more question :)
