### ISSUE TITLE
fix: search users on any search bar is not relevant

### ISSUE THREAD

**Issue by Reaster0** [42Atomys/stud42#281]
### Describe the bug

when i try to search a user (to add as a friend or just to stalk it) it don't find it, and a lot of friends have a similar issue 
i've tried : 
rotrojan
estoffel
asurell

i really don't know the common trait between all of the users i know, but there is one that make them non searchable

### To Reproduce

try to search someone trough any search bar

### Expected behavior

well find the users i want trough the search bar i guess :')

### Version of software

v0.18.3

### Environment

Live (https://s42.app)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42Atomys** [comment]
Thanks for your issue, I just give the code that seems to be involved :
https://github.com/42Atomys/stud42/blob/main/internal/api/api.resolvers.go#LL149-L192

I will takes this issue tommorrow if nobody want to do it

**Comment by 42Atomys** [comment]
I think replace the search engine with a more relevant tool instead of postgresql.

I want to try https://github.com/meilisearch/meilisearch as open source search engine
