### ISSUE TITLE
misc: permission scope on github account is too broad

### ISSUE THREAD

**Issue by wendrul** [42Atomys/stud42#304]
### Please exprime yourself

When connecting the github account upon creation, many unnecessary permissions are requested, such as read/write of repos and more. It might be a good idea to revisit the necessary permissions and reduce the scope to the minimum required.

Also, I revoked the app permissions from github, but there is no way to reconnect the service.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42Atomys** [comment]
Hi, thanks for your issue. 

This is explained in another issue for the scope and the weird reason about "write access" (this is already the minimum scope): 

https://github.com/42Atomys/stud42/issues/277

If you have revoke your GitHub account, yes actually no way to reconnect 😔 This is planned under the "settings/access" page in the future on beta !  

But don't worry, you will be notified when this page has released if your credentials is revoked 😃
