### ISSUE TITLE
feat: integrate wolfsburg campus

### ISSUE THREAD

**Issue by mdabir1203** [42atomys/stud42#359]
### Is your feature request related to a problem? Please describe

I want to add the wolfsburg campus to the map . And I cannot commit . As it showed me this:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/66947064/207735539-b7765bfe-050b-401e-b38a-a8900770c46a.png">

Also the cluster map photos are here.
![cluster1](https://user-images.githubusercontent.com/66947064/207735752-1210176a-37ff-4f23-8cb6-bf649f274435.svg)
![cluster2](https://user-images.githubusercontent.com/66947064/207735756-15cca95c-2121-413c-bcd5-206d82b493db.svg)

### Describe the solution you'd like

I would require your help. As I am doing the commit in github codespaces. 
As for the permission from the staff I can get that for you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42Atomys** [comment]
@mdabir1203 Hi, you need to have gpg install on your computer, every commit must be signed

I give you the documentation about that : https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by 42Atomys** [comment]
@mdabir1203 Maybe linked to the devcontainer git forward setup. Try to push from your computer and not from the devcontainer. 

I will takes a look on gpg issue in the week end

**Comment by mdabir1203** [comment]
I tried to do it, its the same issue in Mac. I tried to install gpg its not happening without admin rights. Can we change it to ssh signed commit ? 


<img width="1068" alt="image" src="https://user-images.githubusercontent.com/66947064/208216106-ba3a5425-baff-4c58-b451-02df0f272bef.png">

**Comment by 42Atomys** [comment]
Yes on Mac, you need to install gpgtools to have gpg and on campus mac you dont have root access.. We can avoid this idea,, MMhhhhhh *thinking*. Focusing on devcontainer. 

Inside the devcontainer, you have a root access through sudo. you can try to fix in inside of it. 
I check the devcontainer install process and gpg / gpg2 as installed inside the container.

**Comment by mdabir1203** [comment]
Found the solution for now. Had to enable this option in github settings. Maybe add it to your pull request documentation :
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/66947064/208318993-dada060a-69b9-45b9-a857-adf732c772ef.png">

**Comment by sungyongcho** [comment]
Hello, i've encountered the same problem as you did, but I was able to resolve them by using this link

https://blog.startsomething.dev/2019/09/29/gpg-%EC%82%AC%EC%9D%B4%EB%8B%9D%EC%9C%BC%EB%A1%9C-commit-verified-%EB%94%B1%EC%A7%80%EB%A5%BC-%EB%B6%99%EC%9D%B4%EC%9E%90/
(yes, it's in korean..)

Even if you are in school, there should be a chance you can install the packages that are needed 

If you need the brew, here is the link https://github.com/kube/42homebrew

**Comment by mdabir1203** [comment]
@sungyongcho  Did you use the github codespaces ? 
Also I tried the 42homebrew  in the school mac :/ it didn't work

I am still facing the same issue even doing all the things .
can you guys refer me what could be the issue. 

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/66947064/210920014-95d88bde-7270-4460-b6f7-cb44622f96b1.png">

**Comment by mdabir1203** [comment]
Finally fixed it. It worked with github codespaces. Made a small step mistake of skipping a step earlier :D . @42Atomys  Let me know if everything is alright

@sungyongcho  Can you also tell me how did you get the exact cluster design
I might have to redit some part of it.

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/66947064/210920749-47e66de2-c8a1-4422-8325-303d35240f34.png">

**Comment by 42Atomys** [comment]
>  @42Atomys Let me know if everything is alright

Congrats, fell free to open a Pull Request with your changes when pushed :) 

> Can you also tell me how did you get the exact cluster design

You already have the cluster design in your initial comment, I think don't understand fine 🤔

**Comment by sungyongcho** [comment]
sorry I got here late, if you mean by the design of the clusters, yes you'd just create with the map you posted

**Comment by mdabir1203** [comment]
Hey @42atomys Is the pull request done yet ? Or do I still need to speak to the staff

**Comment by 42atomys** [comment]
@mdabir1203 A mail as been sent to staff members this Monday, I wait their answers

**Comment by mdabir1203** [comment]
@42atomys  Is there an update for this ?

**Comment by 42atomys** [comment]
> @42atomys  Is there an update for this ? 

@mdabir1203 I still have no answer from any staff since last message 🥲 If you have more success tell me 🙏
