### ISSUE TITLE
misc: don't force me to follow you/star the project

### ISSUE THREAD

**Issue by Anarbb** [42Atomys/stud42#387]
### Please exprime yourself

It's not harmful, but really creepy when an application starts following and starring projects, just ask people and they will most definitely do it, don't force it on me. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by copeugne** [comment]
I agree it's kind of sketchy.

**Comment by 42Atomys** [comment]
Hi 👋 

Thanks for takes the time to start a discussion, I add a part on FAQ https://github.com/42Atomys/stud42/issues/364 about that (copied as follow) :

--- 
When you arrive to the beta access project, this is a requirement to access to the beta and this is write on this page.
As a requirement, you can accept it, and access to the app or not and you will need to wait the end of the beta, when this requirement will ne be exist anymore 😄

I decide to automate it to not be boring with 2 extra step for me and you.
--- 

I keep open to changes but this change is about automation and not the "requirement to access the beta". 
The alternative way is to ask to link GH account without noisy permissions and check on each site access (cached like 1h) if the user currently follow and star the repo. If yes: all is good, if no: revoke access and go back to beta access page

Best regards,
