### ISSUE TITLE
fix: incorrect freePlacesPerCluster on Vienna campus

### ISSUE THREAD

**Issue by 42lan** [42atomys/stud42#420]
### Describe the bug

The number of `freePlacesPerCluster` is incorrect on Vienna campus.

I suppose that `occupiedWorkspace` does not return a correct value, hence the negative number of `freePlacesPerCluster`.

![Screenshot from 2023-04-05 09-42-03](https://user-images.githubusercontent.com/22397481/230015717-6620b243-05f4-40cb-80ef-2cb2a1acf6ca.png)

### To Reproduce

1. Open [s42.app](https://s42.app/)
2. Select a [Vienna cluster](https://s42.app/clusters/vienna/c1)

### Expected behavior

The expected behavior is the correct evaluation of [freePlacesPerCluster()](https://github.com/42Atomys/stud42/blob/b0a45e0985ccb2afb4bde00b9fb308e4bd873ad1/web/ui/src/containers/clusters/ClusterSidebar.tsx#L46).

### Version of software

v0.22.3

### Environment

Live (https://s42.app)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42Atomys** [comment]
Manual operation are done on each campus to fix invalid locations, a long-term fix in on the way!
