### ISSUE TITLE
fix: offline user appearing in cluster

### ISSUE THREAD

**Issue by TheFoxan12** [42atomys/stud42#502]
### Describe the bug

Since the Mulhouse campus integration, some user who are offline appear online permanently

---

<img width="1989" alt="image" src="https://github.com/42atomys/stud42/assets/87044117/18eac86b-0c50-49c7-8b0e-4c286f902549">
<img width="1165" alt="image" src="https://github.com/42atomys/stud42/assets/87044117/33dfb8c3-d711-43fa-bacc-af0ecd409552">

---

<img width="2343" alt="image" src="https://github.com/42atomys/stud42/assets/87044117/18aa8fa8-68ff-4dbf-a512-407582c941b8">
<img width="1310" alt="image" src="https://github.com/42atomys/stud42/assets/87044117/4e3f8437-996b-4594-8918-3e05cc8094db">

---

Even if their profile on s42 show that they are offline

<img width="319" alt="image" src="https://github.com/42atomys/stud42/assets/87044117/3d1f0d86-f0ee-4486-85ec-d3a57e0d6bf5"></br>
<img width="368" alt="image" src="https://github.com/42atomys/stud42/assets/87044117/3e078c2d-afe8-4f37-bf04-baada3134d7b"></br>
<img width="1409" alt="image" src="https://github.com/42atomys/stud42/assets/87044117/4976ab2d-ce50-4ef5-9929-fe90102b7872">

---

If someone is really connected where there is a bugged user, the bugged user appears instead of the really connected 
user.

---

Otherwise, everything works great

<img width="2477" alt="image" src="https://github.com/42atomys/stud42/assets/87044117/f19a0048-3248-46fb-8737-5df58d474dcb">
<img width="1009" alt="image" src="https://github.com/42atomys/stud42/assets/87044117/4f98ae59-080f-4739-a65a-0e1c2b7cc00e">

---

### To Reproduce

It didn't change since the integration, just go to the Mulhouse K0 or K1

### Expected behavior

They shouldn't be displayed because they are offline.

### Version of software

v0.29

### Environment

Live (https://s42.app)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42atomys** [comment]
hello @TheFoxan12, I perform a manual operation to detect and close inactive locations on Mulhouse campus. The incident is close and the long-term resolution will be implemented soon, actually only Paris have the automatic detection due to consumation of this detector. 

I will keep you up to date on Discord :)

**Comment by 42atomys** [comment]
Relative fix apply directly #503
