### ISSUE TITLE
 fix:  redirect settings/profile

### ISSUE THREAD

**Issue by aroualid** [42atomys/stud42#578]
### Describe the bug

hi, when I connect discord, github or spotify, the website redirects me to "https://s42.app/settings/accounts" but the page dosen't exist, the correct redirection is "https://s42.app/settings/profile"

### To Reproduce

try to connect spotify github or discord on  "https://s42.app/settings/profile"

### Version of software

v0.31.1

### Environment

Sandbox (https://sandbox.s42.dev)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42atomys** [comment]
Hi @aroualid thanks for your report, I will works to fix that quickly 💜
